# Mid EXAM : Tools and Techniques Data Science 

# Task 1: ( 5 Marks)  Warp up 

# Note : Rename the file with your name and id and also mention your name and id inside here 

In [1]:
# Q1. Here, we take each element in the list a (temporarily assigning it the value i) 
a = [5, 10, 15, 20]

In [ ]:
# (i)	Find the square each element in the list. This creates a new list called b and does not modify a through data comprehension.

In [6]:
a = [5, 10, 15, 20]
b = [x**2 for x in a]
print(b)

[25, 100, 225, 400]


In [7]:
# (ii)	Write a conditional statement of only squaring the elements if the element is not equal to 10.
a = [5, 10, 15, 20]
b = [x**2 for x in a if x != 10]
print(b)


[25, 225, 400]


In [ ]:
# Q2. (i) Write the command of random samples from a uniform distribution between 0 and 1? 

In [ ]:
import numpy as np 

In [12]:
random_number = np.random.uniform(0, 1)
print(random_number)


0.6801244243349809


In [ ]:
#(ii)	Write the command to slice the column 1? 

In [30]:
data = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]

column_1 =[row[1] for row in data]
print(column_1)

[2, 5, 8]


In [ ]:
#(iii)	Write the command of first and third elements in column 1?

In [31]:
data = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]

first = data[0][1]
third = data[2][1]

print(first, third)

2 8


In [ ]:
#(iv)	 Write the command of returns an 8 x 4 array

In [32]:
import numpy as np

arr_8x4 = np.zeros((8, 4))
print(arr_8x4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
import pandas as pd 

In [ ]:
#Q3. Create a Series that looks like this below:
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [34]:
data = {'Flour': '4 cups',
        'Milk': '1 cup',
        'Eggs': '2 large',
        'Spam': '1 can'}

dinner = pd.Series(data, name='Dinner')

print(dinner)

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object


In [ ]:
# Q  4 Create the Data frame  as th output[27]

In [35]:
data = {'Apples': [35, 41],
        'Bananas': [21, 34]}

df = pd.DataFrame(data, index=['2017Sales', '2018Sales'])

In [36]:
df

Apple  Banana
2017Sales     35      21
2018Sales     41      34

In [ ]:
#Q4. create Dataframe then find imputation for these missing NaN in the out[47]

In [21]:
data = {
    'Age': [23.0, 39.0, 45.0, np.nan],
    'Gender': ['M', 'F', 'F', 'M'],
    'Income': [24200.0, np.nan, 45390.0, np.nan],
    'Religion': ['Muslim', 'Christian', np.nan, 'Muslim']
}

df = pd.DataFrame(data)
df


Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F      NaN  Christian
2  45.0      F  45390.0        NaN
3   NaN      M      NaN     Muslim

In [ ]:
df

Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F      NaN  chirstian
2  45.0      F  45390.0        NaN
3   NaN      M      NaN     Muslim

In [ ]:
#Q4(i)	Compute the appropriate missing value in income attribute?

In [46]:
import pandas as pd

df['Income'].fillna(df['Income'].mean(), inplace=True)

print(df)

      Name  Age   Income
0     John   32  50000.0
1    Alice   28  60000.0
2      Bob   45  70000.0
3    Emily   36  60000.0
4  Michael   40  60000.0


In [ ]:
#(ii)	Compute the appropriate missing values in religion attribute? 

In [ ]:
df['Religion'].fillna('Unknown', inplace=True)

In [28]:
df

Gender   Income   Religion
0      M  24200.0     Muslim
1      F  34795.0  Christian
2      F  45390.0    Unknown
3      M  34795.0     Muslim

In [ ]:
#(iii)	Drop the columns where any of the elements is nan

In [26]:
df = df.dropna(axis=1)

df

Gender   Income   Religion
0      M  24200.0     Muslim
1      F  34795.0  Christian
2      F  45390.0    Unknown
3      M  34795.0     Muslim

In [24]:
#(iv)	Keep only the rows with at least 2 non-na values

In [25]:
df = df.dropna(thresh=2)
df

Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F  34795.0  Christian
2  45.0      F  45390.0    Unknown
3   NaN      M  34795.0     Muslim